name: diorite
description: "A Character Manager"
publish_to: 'none'
version: 1.2.6+7

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  path_provider: 2.1.0
  path: ^1.9.1
  file_selector: ^1.1.0
  dotted_border: ^3.1.0
  image: ^4.1.3
  flutter_staggered_grid_view: ^0.7.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: ChironGoRoundTC
      fonts:
        - asset: lib/assets/Chiron.ttf
    - family: Kalam
      fonts:
        - asset: lib/assets/Kalam-Regular.ttf
        - asset: lib/assets/Kalam-Bold.ttf
          weight: 700
        - asset: lib/assets/Kalam-Light.ttf
          weight: 200
